### ISSUE TITLE
Where should I execute `kninja.py`?

### ISSUE THREAD

**Issue by agrexgh** [rabinv/kninja#2]
As the title says, I can't understand where to execute `kninja.py`.

Though I may ask a stupid question because I'm noob for linux kernel build,
could you answer me?

I cloned https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git,
and I guess I should execute somewhere in the source tree.

**Comment by vitkyrka** [comment]
You should run it from the same place from which you would run `make` to build the kernel when not using kninja, which is usually the root of the source tree.  You should have already configured your kernel using `make defconfig` or similar.

**Comment by agrexgh** [comment]
> You should run it from the same place from which you would run make to build the kernel when not using kninja, which is usually the root of the source tree. You should have already configured your kernel using make defconfig or similar.

Thank you, I'll try this!
